language: php

addons:
  postgresql: "9.5"
  apt:
    packages:
      - chromium-chromedriver

services:
  - docker
  - postgresql

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm
    - $HOME/.nvm

env:
  global:
    - DB=pgsql

matrix:
  include:
    - php: 7.0
      env: MOODLE_BRANCH=MOODLE_35_STABLE

    - php: 7.0
      env: MOODLE_BRANCH=MOODLE_36_STABLE NODE=8.9

    - php: 7.1
      env: MOODLE_BRANCH=MOODLE_37_STABLE

    - php: 7.2
      env: MOODLE_BRANCH=MOODLE_38_STABLE

    - php: 7.3
      env: MOODLE_BRANCH=MOODLE_39_STABLE

before_install:
  - phpenv config-rm xdebug.ini
  - nvm install ${NODE:-14}
  - nvm use ${NODE:-14}
  - cd ../..
  - composer create-project -n --no-dev --prefer-dist moodlerooms/moodle-plugin-ci ci ^2
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"
  - docker run -d -p 127.0.0.1:4444:4444 --net=host -v /dev/shm:/dev/shm selenium/standalone-chrome:3

install:
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci grunt
  - moodle-plugin-ci phpunit --coverage-text
  - moodle-plugin-ci behat --profile chrome
