language: php

sudo: required

addons:
  firefox: "47.0.1"
  apt:
    packages:
      - openjdk-8-jre-headless

services:
  - mysql

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

env:
  global:
    - DB=mysqli

matrix:
  include:
    - php: 7.0
      env: MOODLE_BRANCH=MOODLE_35_STABLE

    - php: 7.0
      env: MOODLE_BRANCH=MOODLE_36_STABLE

    - php: 7.1
      env: MOODLE_BRANCH=MOODLE_37_STABLE

before_install:
  - phpenv config-rm xdebug.ini
  - nvm install 8.9
  - nvm use 8.9
  - cd ../..
  - composer create-project -n --no-dev --prefer-dist moodlerooms/moodle-plugin-ci ci ^2
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat
