language: php

addons:
  postgresql: "9.6"

services:
  - docker
  - postgresql

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm
    - $HOME/.nvm

env:
  global:
    - DB=pgsql

matrix:
  include:
    - php: 7.1
      env: MOODLE_BRANCH=MOODLE_35_STABLE

    - php: 7.2
      env: MOODLE_BRANCH=MOODLE_38_STABLE

    - php: 7.3
      env: MOODLE_BRANCH=MOODLE_39_STABLE

    - php: 7.3
      env: MOODLE_BRANCH=MOODLE_310_STABLE

before_install:
  - phpenv config-rm xdebug.ini
  - cd ../..
  - composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^3
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci grunt
  - moodle-plugin-ci phpunit --coverage-text
  - moodle-plugin-ci behat --profile chrome
